# Generated by Django 3.1.4 on 2021-04-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
